application: appenginetest
version: 1
runtime: python27
api_version: 1
threadsafe: no
#log_level: DEBUG

libraries:
- name: django
  version: "1.4"
- name: webapp2
  version: latest

env_variables:
  DJANGO_SETTINGS_MODULE: 'conf.django_conf'
  

includes:
- conf/env.yaml
    
handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css 

- url: .*
  script: main.py
