application: appenginetest
version: 1
runtime: python
api_version: 1
threadsafe: no
#log_level: DEBUG

includes:
- conf/env.yaml
    
handlers:
- url: /js
  static_dir: js

- url: /css
  static_dir: css 

- url: .*
  script: main.py
